# Generated by Django 4.2 on 2024-10-25 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivo', '0009_cultivodata_rendimiento_normalizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendimientoAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateField(auto_now_add=True)),
                ('rendimiento_real_promedio', models.FloatField(blank=True, null=True)),
                ('rendimiento_relativo_promedio', models.FloatField(blank=True, null=True)),
                ('coef_variacion_real', models.FloatField(blank=True, null=True)),
                ('coef_variacion_relativo', models.FloatField(blank=True, null=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendimientos_ambiente', to='cultivo.cultivo')),
            ],
        ),
    ]
