# Generated by Django 4.2 on 2024-10-26 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo', '0009_cultivodata_rendimiento_normalizado'),
        ('ambientes', '0001_initial'),
        ('rendimiento_ambiente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendimientoambiente',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendimientos', to='ambientes.ambiente'),
        ),
        migrations.AlterUniqueTogether(
            name='rendimientoambiente',
            unique_together={('cultivo', 'ambiente')},
        ),
    ]
