# Comando para build de la imagen de docker.
# docker build -t lab-front-test:latest -f ./frontend/Dockerfile ./frontend/

# docker-compose -f prod.docker-compose.yml up -d
# docker-compose -f prod.docker-compose.yml up -d --build

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: STMGIS
    volumes:
      - bd_data:/data/db
    networks:
      - net

  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/__pycache__/
    ports:
      - "8000:80"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    environment:
      - DEBUG=0
      - DB_NAME=STMGIS
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - net

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
     - "4200:4200"
    depends_on:
     - backend
    networks:
      - net

  # Proxy inverso para el frontend.
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./proxyinverso.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - net

volumes:
  bd_data:

networks:
  net:
    driver: bridge