# Comando para build de la imagen de docker.
# docker build -t lab-front-test:latest -f ./frontend/Dockerfile ./frontend/

# docker-compose -f prod.docker-compose.yml up -d
# docker-compose -f prod.docker-compose.yml up -d --build

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: STMGIS
    volumes:
      - bd_data:/data/db
    networks:
      - net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - net
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/__pycache__/
    ports:
      - "8000:80"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - net

  frontend:
    build: ./frontend
#    ports:
#      - "81:80"
    networks:
      - net

  # Proxy inverso para el frontend.
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./proxyinverso.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - net

volumes:
  bd_data:

networks:
  net:
    driver: bridge