# Generated by Django 4.2 on 2024-09-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='empresas',
            field=models.ManyToManyField(blank=True, to='empresa.empresa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('responsable', 'Responsable')], default='responsable'),
        ),
    ]
