# Generated by Django 4.2 on 2024-09-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='empresas',
            field=models.ManyToManyField(related_name='users', to='empresa.empresa'),
        ),
    ]
