# Generated by Django 4.2 on 2024-10-01 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cultivo',
            old_name='sub_total',
            new_name='sup_total',
        ),
    ]
