# Generated by Django 4.2 on 2024-10-03 19:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo', '0002_rename_sub_total_cultivo_sup_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultivoCSV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo_csv', models.FileField(upload_to='cultivo_csvs/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_csv', to='cultivo.cultivo')),
            ],
            options={
                'ordering': ['fecha_subida'],
            },
        ),
    ]
