# Generated by Django 4.2 on 2024-10-04 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo', '0003_cultivocsv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CultivoCSV',
        ),
    ]
