# Generated by Django 4.2 on 2024-10-04 16:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo', '0004_delete_cultivocsv'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultivoCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_csv', models.FileField(upload_to='csv_files/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_files', to='cultivo.cultivo')),
            ],
            options={
                'verbose_name': 'Cultivo CSV',
                'verbose_name_plural': 'Cultivo CSVs',
            },
        ),
        migrations.CreateModel(
            name='CultivoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo_csv', models.CharField(max_length=255)),
                ('punto_geografico', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('lote', models.CharField(max_length=255)),
                ('conjunto_datos', models.CharField(max_length=255)),
                ('producto', models.CharField(max_length=255)),
                ('id_obj', models.IntegerField()),
                ('distancia', models.FloatField()),
                ('curso', models.FloatField()),
                ('duracion', models.FloatField()),
                ('elevacion', models.FloatField()),
                ('tiempo', models.DateTimeField()),
                ('cuenta_area', models.FloatField()),
                ('anch_fja', models.FloatField()),
                ('desviacion_y', models.FloatField()),
                ('flj_cultivos_m', models.FloatField()),
                ('humedad', models.FloatField()),
                ('masa_rend_humedo', models.FloatField()),
                ('vol_rend_humedo', models.FloatField()),
                ('masa_rend_seco', models.FloatField()),
                ('vol_rend_seco', models.FloatField()),
                ('humedad_2', models.FloatField()),
                ('temp_aire', models.FloatField()),
                ('vel_viento', models.FloatField()),
                ('temp_suelo', models.FloatField()),
                ('num_paso', models.IntegerField()),
                ('velocidad', models.FloatField()),
                ('prod', models.FloatField()),
                ('flj_cultivos_v', models.FloatField()),
                ('fecha', models.DateField()),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='cultivo.cultivo')),
                ('cultivo_csv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_rows', to='cultivo.cultivocsv')),
            ],
            options={
                'verbose_name': 'Cultivo Data',
                'verbose_name_plural': 'Cultivo Data',
            },
        ),
    ]
