# Generated by Django 4.2 on 2024-10-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo', '0008_remove_cultivodata_prod_cultivodata_rendimiento_real_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivodata',
            name='rendimiento_normalizado',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
