# Generated by Django 4.2 on 2024-11-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo', '0009_cultivodata_rendimiento_normalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
