# Generated by Django 4.2 on 2024-11-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo', '0010_alter_cultivo_nombre'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cultivodata',
            index=models.Index(fields=['cultivo'], name='idx_cultivo'),
        ),
        migrations.AddIndex(
            model_name='cultivodata',
            index=models.Index(fields=['cultivo', 'fecha'], name='idx_cultivo_fecha'),
        ),
    ]
