# Generated by Django 4.2 on 2024-09-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
