# Generated by Django 4.2 on 2024-09-27 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='owner',
        ),
    ]
