# Generated by Django 4.2 on 2024-09-27 23:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('humedad_minima', models.FloatField()),
                ('humedad_maxima', models.FloatField()),
                ('variacion_admitida', models.FloatField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nutrientes', models.JSONField()),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
