# Generated by Django 4.2 on 2024-09-27 23:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente_geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('ia', models.IntegerField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=100, null=True)),
                ('sist_prod', models.CharField(blank=True, max_length=100, null=True)),
                ('zona', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_suelo', models.IntegerField(blank=True, null=True)),
                ('posicion', models.CharField(blank=True, max_length=100, null=True)),
                ('prof', models.CharField(blank=True, max_length=100, null=True)),
                ('restriccion', models.CharField(blank=True, max_length=100, null=True)),
                ('ambiente', models.CharField(blank=True, max_length=100, null=True)),
                ('idA', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
