# Generated by Django 4.2 on 2024-09-27 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campo', '0001_initial'),
        ('ambientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='campo.campo'),
        ),
    ]
