# Generated by Django 4.2 on 2024-09-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiente',
            name='area',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='has_siembra',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='ia',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='posicion',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='profundidad',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='restriccion',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='sist_prod',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='tipo_suelo',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='zona',
        ),
        migrations.AddField(
            model_name='ambiente',
            name='datos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
