# Generated by Django 4.2 on 2024-09-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
