# Generated by Django 4.2 on 2024-09-23 23:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0002_remove_ambiente_area_remove_ambiente_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='ambiente_geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
