# Generated by Django 4.2 on 2024-09-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0003_alter_ambiente_ambiente_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='ambiente',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='ia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='id_ambiente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='id_ambiente_int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='posicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='profundidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='restriccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='sist_prod',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='tipo_suelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='zona',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
