# Generated by Django 4.2 on 2024-09-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0004_ambiente_ambiente_ambiente_area_ambiente_ia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='profundidad',
            field=models.CharField(blank=True, null=True),
        ),
    ]
