# Generated by Django 4.2 on 2024-09-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0005_alter_ambiente_profundidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='ambiente',
            field=models.CharField(blank=True, null=True),
        ),
    ]
