# Generated by Django 4.2 on 2024-09-25 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0006_alter_ambiente_ambiente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiente',
            name='ambiente',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='area',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='ia',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='id_ambiente',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='id_ambiente_int',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='posicion',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='profundidad',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='restriccion',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='sist_prod',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='tipo_suelo',
        ),
        migrations.RemoveField(
            model_name='ambiente',
            name='zona',
        ),
    ]
