# Generated by Django 4.2 on 2024-09-27 18:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('superficie', models.FloatField()),
                ('departamento', models.CharField(max_length=100)),
                ('shapePoligon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
