# Generated by Django 4.2 on 2024-09-20 21:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='shapePoligon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(default=(1, 0, 0, 0, 1), srid=4326),
            preserve_default=False,
        ),
    ]
