# Generated by Django 4.2 on 2024-09-23 13:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='shapePoligon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
