# Generated by Django 4.2 on 2024-09-27 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('campo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='empresa.empresa'),
        ),
    ]
