# Generated by Django 4.2 on 2024-09-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0002_campo_shapepoligon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campo',
            name='shapePoligon',
        ),
    ]
